CREATE TABLE Prueba(
        idPrueba NUMBER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100),
    apellido varchar(100)
);

SELECT * FROM Prueba;

INSERT INTO prueba (nombre,apellido) values ('Steven','Sis');