CREATE TABLE Prueba(
        idPrueba NUMBER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100),
    apellido varchar(100)
);

SELECT * FROM Prueba;

INSERT INTO prueba (nombre,apellido) values ('Steven','Sis');

CREATE TABLE tipo_U (
    idTipo_U NUMBER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(20)
);

INSERT INTO tipo_U (nombre) VALUES('admin');
INSERT INTO tipo_U (nombre) VALUES('client');

CREATE TABLE usuario(
    idUsuario NUMBER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50),
    apellido VARCHAR(50),
    pass VARCHAR(50),
    email VARCHAR(50),
    nacimieno DATE,
    credito DECIMAL,
    confirmacion NUMBER,
    idTipo_U NUMBER,
    token VARCHAR(250),
    FOREIGN KEY (idtipo_U) REFERENCES tipo_U (idTipo_U)
);



INSERT INTO usuario (nombre,apellido,pass,email,nacimieno,idTipo_U, confirmacion) VALUES ('201706357','sis','21232f297a57a5a743894a0e4a801fc3','201706357',TO_DATE('12/01/2016', 'DD/MM/YYYY'),1,1);

INSERT INTO usuario (nombre,apellido,pass,email,nacimieno,credito, idTipo_U) VALUES ('201706357','sis','admin','aaronsishernandez@gmail.com',TO_DATE('12/01/2016', 'DD/MM/YYYY'),10000.00,2);

SELECT * FROM tipo_u;
SELECT * FROM usuario;

SELECT * FROM usuario WHERE email='201706357' AND pass='admin';

UPDATE usuario SET confirmacion=1 WHERE token='eyJhbGciOiJIUzI1NiJ9.cHJ1ZWJhc2lzQGdtYWlsLmNvbQ.WV0tT9CXqHixs7zvqJw2rL3AZBL-azR1irrX2bbZ2eo';

TRUNCATE TABLE usuario;
DROP TABLE usuario;